"""Compare the rule baseline against the ML model.

Two evaluations, and only one of them can answer "is ML better?":

  1. Held-out article types, synthetic labels - measures whether the model
     induced the heuristic and transferred it to unseen garment types. The rule
     baseline scores 1.000 here BY CONSTRUCTION (it produced the labels); that's
     reported to make the circularity visible, not as a comparison.

  2. Author-reviewed pairs - labelled by hand without reference to the rules, and
     deliberately including cases the rules were expected to fail. This is the
     only non-circular comparison.

A trivial always-compatible baseline is included too, because "rule F1 = 0.60,
therefore rules win" would be misleading if guessing "yes" scores 0.75.

Run:  python scripts/evaluate_ml.py
Out:  docs/ml_evaluation_results.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.compatibility import pair_compatibility  # noqa: E402
from src.data import get_product  # noqa: E402
from src.ml.features import FEATURE_COLUMNS  # noqa: E402

MODEL_PATH = ROOT / "models" / "compatibility_model.joblib"
DATASET = ROOT / "data" / "ml_training" / "compatibility_pairs.csv"
HUMAN = ROOT / "data" / "ml_training" / "human_validation.csv"
OUT = ROOT / "docs" / "ml_evaluation_results.json"

# The same cut used to generate the synthetic labels. Fixed in advance and NOT
# tuned on the human set - tuning a threshold on 65 rows would be overfitting a
# validation set and reporting it as a result.
RULE_THRESHOLD = 0.70
HYBRID_WEIGHT_ML = 0.6


def score_set(name: str, y_true, y_score, threshold: float) -> dict:
    y_pred = (np.asarray(y_score) >= threshold).astype(int)
    result = {
        "system": name,
        "accuracy": round(float(accuracy_score(y_true, y_pred)), 4),
        "precision": round(float(precision_score(y_true, y_pred, zero_division=0)), 4),
        "recall": round(float(recall_score(y_true, y_pred, zero_division=0)), 4),
        "f1": round(float(f1_score(y_true, y_pred, zero_division=0)), 4),
        "n": int(len(y_true)),
    }
    if len(set(y_true)) > 1:
        result["roc_auc"] = round(float(roc_auc_score(y_true, y_score)), 4)
    return result


def rule_scores_for(frame: pd.DataFrame) -> np.ndarray:
    """Rule-engine compatibility for each pair, recomputed from the catalog."""
    scores = []
    for row in frame.itertuples(index=False):
        a, b = get_product(row.id_a), get_product(row.id_b)
        scores.append(pair_compatibility(a, b) if a and b else 0.0)
    return np.asarray(scores)


def table(rows: list[dict]) -> str:
    header = f"{'system':<26}{'acc':>8}{'prec':>8}{'rec':>8}{'f1':>8}{'auc':>8}"
    lines = [header, "-" * len(header)]
    for row in rows:
        auc = row.get("roc_auc")
        lines.append(
            f"{row['system']:<26}{row['accuracy']:>8.3f}{row['precision']:>8.3f}"
            f"{row['recall']:>8.3f}{row['f1']:>8.3f}"
            f"{(f'{auc:.3f}' if auc is not None else 'n/a'):>8}"
        )
    return "\n".join(lines)


def main() -> None:
    if not MODEL_PATH.exists():
        raise SystemExit("Run scripts/train_compatibility_model.py first.")

    bundle = joblib.load(MODEL_PATH)
    pipeline = bundle["pipeline"]
    held_out_types = set(bundle["held_out_article_types"])

    results: dict[str, list[dict]] = {}

    # ------------------------------------------------------------------
    # 1. Held-out article types, synthetic labels
    # ------------------------------------------------------------------
    frame = pd.read_csv(DATASET)
    test = frame[
        frame["articleType_a"].isin(held_out_types)
        | frame["articleType_b"].isin(held_out_types)
    ]
    y_true = test["compatible"].to_numpy()
    ml_proba = pipeline.predict_proba(test[FEATURE_COLUMNS])[:, 1]

    synthetic = [
        score_set("Rule baseline", y_true, test["rule_score"].to_numpy(), RULE_THRESHOLD),
        score_set("ML model", y_true, ml_proba, 0.5),
    ]
    results["held_out_synthetic_labels"] = synthetic

    print("=" * 74)
    print("1. HELD-OUT ARTICLE TYPES  ·  SYNTHETIC (rule-generated) LABELS")
    print(f"   held out: {sorted(held_out_types)}")
    print("=" * 74)
    print(table(synthetic))
    print(
        "\n   The rule baseline scores a perfect 1.000 BY CONSTRUCTION: these\n"
        "   labels were generated by that very rule. It is circular and is shown\n"
        "   only to make the circularity explicit. The ML number is the real one\n"
        "   here - it measures how well the heuristic was induced from raw\n"
        "   attributes and transferred to garment types never seen in training."
    )

    # ------------------------------------------------------------------
    # 2. Author-reviewed labels - the real comparison
    # ------------------------------------------------------------------
    human = pd.read_csv(HUMAN)
    y_human = human["human_label"].to_numpy()
    rule_scores = rule_scores_for(human)
    ml_human = pipeline.predict_proba(human[FEATURE_COLUMNS])[:, 1]
    hybrid = HYBRID_WEIGHT_ML * ml_human + (1 - HYBRID_WEIGHT_ML) * rule_scores

    # A trivial reference point. Without it, "rule F1 = 0.60, therefore rules
    # win" is a misleading conclusion: if 60% of pairs are compatible, a system
    # that blindly answers "yes" scores F1 0.75 and beats both real systems.
    # Any claim of value has to clear this bar first.
    always_yes = np.ones(len(y_human))

    comparison = [
        score_set("0. Always-compatible", y_human, always_yes, 0.5),
        score_set("A. Rule baseline", y_human, rule_scores, RULE_THRESHOLD),
        score_set("B. ML model", y_human, ml_human, 0.5),
        score_set("C. Hybrid (0.6ML+0.4rule)", y_human, hybrid, 0.5),
    ]
    results["human_reviewed_labels"] = comparison
    results["human_set_positive_rate"] = round(float(y_human.mean()), 4)

    print("\n" + "=" * 74)
    print("2. AUTHOR-REVIEWED LABELS  ·  the only non-circular comparison")
    print("=" * 74)
    print(table(comparison))

    # ------------------------------------------------------------------
    # 3. The adversarial subset
    # ------------------------------------------------------------------
    adversarial = human["expected_rule_disagreement"] == 1
    if adversarial.any():
        sub_true = y_human[adversarial.to_numpy()]
        sub = [
            score_set("A. Rule baseline", sub_true,
                      rule_scores[adversarial.to_numpy()], RULE_THRESHOLD),
            score_set("B. ML model", sub_true,
                      ml_human[adversarial.to_numpy()], 0.5),
            score_set("C. Hybrid", sub_true,
                      hybrid[adversarial.to_numpy()], 0.5),
        ]
        results["adversarial_subset"] = sub
        print("\n" + "=" * 74)
        print(f"3. ADVERSARIAL SUBSET ({int(adversarial.sum())} pairs where the "
              "rules were expected to be wrong)")
        print("=" * 74)
        print(table(sub))

    # ------------------------------------------------------------------
    # 4. Per-pair disagreements, for inspection
    # ------------------------------------------------------------------
    human = human.assign(
        rule_score=rule_scores.round(3),
        rule_pred=(rule_scores >= RULE_THRESHOLD).astype(int),
        ml_proba=ml_human.round(3),
        ml_pred=(ml_human >= 0.5).astype(int),
    )
    disagree = human[human["rule_pred"] != human["ml_pred"]]
    print("\n" + "=" * 74)
    print(f"4. WHERE RULE AND ML DISAGREE ({len(disagree)} of {len(human)} pairs)")
    print("=" * 74)
    if disagree.empty:
        print("   None. The model reproduces the rule's decisions exactly on this set,")
        print("   which is the expected outcome of training on rule-generated labels.")
    else:
        for row in disagree.itertuples(index=False):
            correct = "ML right" if row.ml_pred == row.human_label else "rule right"
            print(f"   {row.desc_a:<28} + {row.desc_b:<28} "
                  f"human={row.human_label} rule={row.rule_pred}"
                  f"({row.rule_score:.2f}) ml={row.ml_pred}({row.ml_proba:.2f})  "
                  f"-> {correct}")

    # ------------------------------------------------------------------
    # 5. Verdict
    # ------------------------------------------------------------------
    trivial_f1 = comparison[0]["f1"]
    rule_f1 = comparison[1]["f1"]
    ml_f1 = comparison[2]["f1"]
    hybrid_f1 = comparison[3]["f1"]
    rule_auc = comparison[1].get("roc_auc")
    ml_auc = comparison[2].get("roc_auc")
    improves = ml_f1 > rule_f1 or hybrid_f1 > rule_f1

    results["verdict"] = {
        "trivial_f1": trivial_f1,
        "rule_f1": rule_f1,
        "ml_f1": ml_f1,
        "hybrid_f1": hybrid_f1,
        "rule_auc": rule_auc,
        "ml_auc": ml_auc,
        "ml_improves_over_rules": bool(improves),
        "anything_beats_trivial_on_f1": bool(
            max(rule_f1, ml_f1, hybrid_f1) > trivial_f1
        ),
        "decision": (
            "Integrate the ML scorer into the production ranking path."
            if improves else
            "Do NOT integrate. Keep the rule engine as the production recommender; "
            "retain the ML model as a documented, reproducible experiment."
        ),
    }

    print("\n" + "=" * 74)
    print("VERDICT")
    print("=" * 74)
    print(f"   trivial F1 {trivial_f1:.3f}  |  rule F1 {rule_f1:.3f}  |  "
          f"ML F1 {ml_f1:.3f}  |  hybrid F1 {hybrid_f1:.3f}")
    print(f"   ranking signal (AUC): rule {rule_auc}  ML {ml_auc}  (0.5 = chance)")
    print(f"   ML beats rules? {improves}")
    print(f"   {results['verdict']['decision']}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(results, indent=2), encoding="utf-8")
    print(f"\nWrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
